# Describes the format for available RainMachine services

---
pause_watering:
  description: Pause all watering for a number of seconds.
  fields:
    seconds:
      description: The number of seconds to pause.
      example: 30
start_program:
  description: Start a program.
  fields:
    program_id:
      description: The program to start.
      example: 3
start_zone:
  description: Start a zone for a set number of seconds.
  fields:
    zone_id:
      description: The zone to start.
      example: 3
    zone_run_time:
      description: The number of seconds to run the zone.
      example: 120
stop_all:
  description: Stop all watering activities.
stop_program:
  description: Stop a program.
  fields:
    program_id:
      description: The program to stop.
      example: 3
stop_zone:
  description: Stop a zone.
  fields:
    zone_id:
      description: The zone to stop.
      example: 3
unpause_watering:
  description: Unpause all watering.
